MeetupView
js-tasks-ru/vue-20210511_volkov-cmd-su pull request #10
Opened 2021-06-02 16:36 UTC by tigr013

2021-06-02 16:36 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-02 17:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-06-03 18:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-06-03 19:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-06-03 19:46 UTC, ShGKme requested changes
Требуется поправить имя класса в 03-sfc/02-FormGroup

2021-06-03 19:46 UTC, ShGKme commented on 02-components/06-MeetupView/MeetupView.js
> +      <MeetupCover :title="meetup.title" :link="this.meetup.imageId ? getImage : ''"/>
`this` в шаблоне не нужен.

2021-06-03 19:46 UTC, ShGKme commented on 02-components/06-MeetupView/MeetupView.js
> +    },
Вычисляемое свойства - это именно свойства. Для них описывается функция, с помощью которой Vue будет вычислять значение вычисляемого свойства, но оно остаётся свойством. По этой причине вычисляемые свойства принято называть, как свойства, а не как функции (не с глагола, без get).

2021-06-03 19:46 UTC, ShGKme commented on 03-sfc/02-FormGroup/components/FormGroup.vue
>      <!-- <input /> -->
`v-if="label"` можно установить непосредственно на `label`. `Template` здесь не нужен

2021-06-03 19:46 UTC, ShGKme commented on 03-sfc/02-FormGroup/components/FormGroup.vue
> +  <div class="form-group" :class="inline ? '.form-group_inline' : ''">
Во Vue, когда требуется добавить класс по условию, удобно использовать синтаксис привязки класса объектом, где ключ - имя класса, а значение - логическое значение, которое обозначает, что класс требуется добавить.
https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax

Класс `.form-group_inline`  должен быть без точки. В условии точка используется для индикации классов, по аналогии с селекторами.

2021-06-09 17:00 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-09 17:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-06-09 20:42 UTC, ShGKme approved these changes
Все задачи приняты 🎉

2021-06-09 20:43 UTC, merged